spring:
  application:
    name: @project.name@

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

  tracing:
    enabled: true
    propagation:
      type: w3c
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
